// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pavaDec
NumericMatrix pavaDec(List cpY, NumericVector thresholds, NumericVector w);
RcppExport SEXP _isodistrreg_pavaDec(SEXP cpYSEXP, SEXP thresholdsSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cpY(cpYSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type thresholds(thresholdsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(pavaDec(cpY, thresholds, w));
    return rcpp_result_gen;
END_RCPP
}
// pavaCorrect
NumericMatrix pavaCorrect(NumericMatrix y);
RcppExport SEXP _isodistrreg_pavaCorrect(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(pavaCorrect(y));
    return rcpp_result_gen;
END_RCPP
}
