# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pavaDec <- function(cpY, thresholds, w) {
    .Call(`_isodistrreg_pavaDec`, cpY, thresholds, w)
}

pavaCorrect <- function(y) {
    .Call(`_isodistrreg_pavaCorrect`, y)
}

