# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

idrHazardCpp <- function(w, W, Y, posY, y) {
    .Call(`_isodistrreg_idrHazardCpp`, w, W, Y, posY, y)
}

isoCdf_sequential <- function(w, W, Y, posY, y) {
    .Call(`_isodistrreg_isoCdf_sequential`, w, W, Y, posY, y)
}

pavaCorrect <- function(y) {
    .Call(`_isodistrreg_pavaCorrect`, y)
}

